name: Update requirements.txt

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pur

      - name: Update requirements.txt with pur
        run: pur -r requirements.txt

      - name: Check for Changes
        run: |
          if git diff --exit-code requirements.txt; then
            echo "No changes detected."
            exit 0
          fi

      - name: Commit and Push Changes
        run: |
          BRANCH_NAME="chore/update-requirements-$(date +'%Y%m%d%H%M%S')"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH_NAME"
          git add requirements.txt
          git commit -m "Update requirements.txt to latest versions"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Update requirements.txt to latest versions" \
            --body "" \
            --head "${{ env.BRANCH_NAME }}" \
            --base main \
            --label dependencies \
            --label github_actions
